---
#################################################################
# Parameters
#################################################################
# user_list: list of user to create
# user_group: user need multi-groups

- name: Create group and user
  block:
    - name: Create user group
      group:
        name: "{{ item.group }}"
        system: yes
        state: present
        gid: "{{ item.group_id }}"
      with_items:
        - "{{ user_list }}"
        
    - name: Create nologin user 
      user:
        name: "{{ item.user }}"
        comment: "{{ item.user }} user"
        uid: "{{ item.user_id }}"
        group: "{{ item.group }}"
        home: "{{ item.user_home }}"
        shell: "/bin/bash"
      with_items:
        - "{{ user_list }}"
    
    - name: Append user to groups
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: yes
      with_items: "{{ user_group }}"
      when: user_group is defined    
    
  become: yes
