---
#################################################################
# Parameters
#################################################################
# file_path: path of file
# file_pattern: pattern to find files

- name: Find {{ file_pattern }} under {{ file_path }} to remove
  block:
    - name: check does {{ file_path }} exists
      stat:
        path: "{{ file_path }}"
      register: path_exist
      
    - name: List old files under {{ file_path }}
      shell: "find {{ file_path }} -name {{ file_pattern }}"
      register: remove_files
      when: path_exist.stat.exists == true
    
    - name: Remove old files under {{ file_path }}
      file: 
        path: "{{ item }}"
        state: absent
      with_items: "{{ remove_files.stdout_lines }}" 
      when: path_exist.stat.exists == true
    
    