---
#################################################################
# Parameters
#################################################################
# mca_was_dir: was path
# wasadmin: wasadmin info

- name: Replace webadmin config
  block:
    - name: Generate {{ mca_was_dir }}/MCA/WEB-INF/classes/log4j.xml ( 1/3 )
      template:
        src: webadmin/MCA/WEB-INF/classes/log4j.xml.j2
        dest: "{{ mca_was_dir }}/MCA/WEB-INF/classes/log4j.xml"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0644
        
    - name: Generate {{ mca_was_dir }}/MCA/WEB-INF/config/props/bxi-config-mca.properties ( 2/3 )
      template:
        src: "webadmin/MCA/WEB-INF/config/props/bxi-config-mca.properties.j2"
        dest: "{{ mca_was_dir }}/MCA/WEB-INF/config/props/bxi-config-mca.properties"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0644
      vars:
        source: "vip"  
        
    - name: Generate {{ mca_was_dir }}/MCA/WEB-INF/web.xml ( 3/3 )
      template:
        src: "webadmin/MCA/WEB-INF/web.xml.j2"
        dest: "{{ mca_was_dir }}/MCA/WEB-INF/web.xml"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0644
        
  become: yes
  become_user: wasadmin         