---
#################################################################
# Parameters
#################################################################
# jboss_dir : jboss path
# jboss.server_name : jboss domain name, ex. devmcaadmin01_18443
# wasadmin : wasadmin info


- name: Replace jboss config
  block:
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/env.properties ( 1/5 )
      template:
        src: jboss/bin/env.properties.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/env.properties"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0644
    
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/env.sh ( 2/5 )
      template:
        src: jboss/bin/env.sh.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/env.sh"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0755
    
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/logging.properties ( 3/5 )
      template:
        src: jboss/bin/logging.properties.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/logging.properties"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0644
        
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/start.sh ( 4/5 )
      template:
        src: jboss/bin/start.sh.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/start.sh"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0755
        
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/stop.sh ( 5/5 )
      template:
        src: jboss/bin/stop.sh.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/bin/stop.sh"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0755
        
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/configuration/logging.properties ( 1/2 )
      template:
        src: jboss/configuration/logging.properties.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/configuration/logging.properties"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0755    
        
    - name: Generate {{ jboss_dir }}/domains/{{ jboss.server_name }}/configuration/standalone.xml ( 2/2 )
      template:
        src: jboss/configuration/standalone.xml.j2
        dest: "{{ jboss_dir }}/domains/{{ jboss.server_name }}/configuration/standalone.xml"
        owner: "{{ wasadmin.user }}"
        group: "{{ wasadmin.group }}"
        mode: 0755   
        
  become: yes
  become_user: wasadmin         