# local 開發時使用 rhel8/tomcat11 image 當作 ap container, 可用於 debug mode

services:
  rest:
    image: rhel8/tomcat10
    container_name: bpm-elf-backend-local
    ports:
      - "18743:18743"
      - "5005:5005"   # 讓 IDE 透過 JPDA 連線 Debug
    environment:
      - TZ=Asia/Taipei
      - LOG_PATH=/logs
      - JPDA_ENABLED=true  # 只在開發模式啟用 JPDA
      - JPDA_ADDRESS=*:5005
      - JPDA_TRANSPORT=dt_socket
    #    deploy:
    #      replicas: 1
    #      restart_policy:
    #        condition: on-failure
    #        delay: 10s  # 等待 10 秒後再重啟
    #        max_attempts: 5  # 最多重啟 5 次
    #        window: 60s  # 60 秒內最多嘗試 max_attempts 次
    #      update_config:
    #        parallelism: 1 # 每次更新 1 個容器
    #        delay: 10s
    #      resources:
    #        limits: # 個別容器
    #          cpus: "1"
    #          memory: "512M"
    volumes:
      # source code maven 專案需把 ./build 改成 ./target
      - type: bind
        source: ./build/classes/java/main/com
        target: /opt/sw/tomcat/webapps/ROOT/WEB-INF/classes/com
      - type: bind
        source: ./build/resources/main/application.yml
        target: /opt/sw/tomcat/webapps/ROOT/WEB-INF/classes/application.yml
      - type: bind
        source: ./build/resources/main/logback-spring.xml
        target: /opt/sw/tomcat/webapps/ROOT/WEB-INF/classes/logback-spring.xml
      # lib
      - type: bind
        source: ./target/ROOT/WEB-INF/lib
        target: /opt/sw/tomcat/webapps/ROOT/WEB-INF/lib
      # templates
      - type: bind
        source: ./src/main/resources/templates
        target: /data/bpm-elf-backend/templates
      # logs
      - type: bind
        source: ./mockEnv/logs/bpm-elf-backend/localhost
        target: /logs/bpm-elf-backend
      # only hotreload
      - type: bind
        source: ./src/main/resources/tomcat/conf/Catalina/localhost/ROOT.xml
        target: /opt/sw/tomcat/conf/Catalina/localhost/ROOT.xml