# local 開發時使用 rhel8/tomcat11 image 當作 ap container, 可用於 debug mode

services:
  tomcat:
    image: rhel8/tomcat10_logback
    container_name: bpm-elf-backend-dev
    ports:
      - "8080:8080"   # Tomcat 監聽 Web 請求
      - "8443:8443"
    #      - "5005:5005"   # 讓 IDE 透過 JPDA 連線 Debug
    environment:
      - TZ=Asia/Taipei
      - LOG_PATH=/logs
    #      - JPDA_ENABLED=true  # 只在開發模式啟用 JPDA
    #      - JPDA_ADDRESS=*:5005
    #      - JPDA_TRANSPORT=dt_socket
    #    deploy:
    #      replicas: 1
    #      restart_policy:
    #        condition: on-failure
    #        delay: 10s  # 等待 10 秒後再重啟
    #        max_attempts: 5  # 最多重啟 5 次
    #        window: 60s  # 60 秒內最多嘗試 max_attempts 次
    #      update_config:
    #        parallelism: 1 # 每次更新 1 個容器
    #        delay: 10s
    #      resources:
    #        limits: # 個別容器
    #          cpus: "1"
    #          memory: "512M"
    volumes:
      - /opt/sw/tomcat/10/conf/Catalina/localhost/ROOT.xml:/opt/sw/tomcat/conf/Catalina/localhost/ROOT.xml
      - /opt/apps/bpm-elf-backend:/opt/sw/tomcat/webapps/ROOT
      - /data/bpm-elf-backend:/data/bpm-elf-backend # templates
      - /logs/bpm-elf-backend:/logs/bpm-elf-backend # logs