services:
  rest:
    image: bpm-elf-backend:${VERSION}
#    container_name: bpm-elf-backend-dev   # swarm 底下沒用
#    ports:
#      - "18743:18743"
#      - "5005:5005"   # 讓 IDE 透過 JPDA 連線 Debug
#    networks:
#      - webnet   # 自定義 overlay 網路，用於 compose 間互連
    environment:
      - TZ=Asia/Taipei
      - LOG_PATH=/logs
    #          - JPDA_ENABLED=true  # 只在開發模式啟用 JPDA
    #          - JPDA_ADDRESS=*:5005
    #          - JPDA_TRANSPORT=dt_socket
    deploy:
      replicas: ${REPLICAS:-2}
      restart_policy:
        condition: on-failure
        delay: 10s  # 等待 10 秒後再重啟
        max_attempts: 5  # 最多重啟 5 次
        window: 60s  # 60 秒內最多嘗試 max_attempts 次
      update_config:
        parallelism: 1 # 每次更新 1 個容器
        delay: 5s
        order: start-first
      resources:
        limits: # 個別容器
          cpus: "1"
          memory: "512M"
    volumes:
      # artifacts
#      - type: bind
#        source: ${ROOT_DIR}/opt/apps/bpm-elf-backend
#        target: /opt/sw/tomcat/webapps/ROOT
      # templates
      - type: bind
        source: ${ROOT_DIR}/data/bpm-elf-backend/${HOSTNAME}
        target: /data/bpm-elf-backend
      # logs
      - type: bind
        source: ${ROOT_DIR}/logs/bpm-elf-backend/${HOSTNAME}.{{.Task.Slot}}
        target: /logs/bpm-elf-backend
      # only hotreload
#      - type: bind
#        source: ${ROOT_DIR}/opt/sw/tomcat/10/conf/Catalina/localhost/ROOT.xml
#        target: /opt/sw/tomcat/conf/Catalina/localhost/ROOT.xml

  nginx:
    image: nginx:1.28.0-alpine-slim
    ports:
      - "18743:18743"
    volumes:
      - type: bind
        source: ${ROOT_DIR}/opt/sw/bpm-elf-backend/${HOSTNAME}/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
#    networks:
#      - webnet
    environment:
      - TZ=Asia/Taipei
    deploy:
      replicas: ${REPLICAS:-2}
      restart_policy:
        condition: on-failure
        delay: 10s  # 等待 10 秒後再重啟
        max_attempts: 5  # 最多重啟 5 次
        window: 60s  # 60 秒內最多嘗試 max_attempts 次
      update_config:
        parallelism: 1 # 每次更新 1 個容器
        delay: 5s
        order: start-first
      resources:
        limits: # 個別容器
          cpus: "1"
          memory: "512M"
  web:
    image: registry.access.redhat.com/ubi8/nodejs-20:1-73
    # image: registry.access.redhat.com/ubi8/nodejs-20:1-74
    # image: node:20.19.1-alpine3.21
    working_dir: /app
    volumes:
      - type: bind
        source: ${ROOT_DIR}/opt/sw/bpm-elf-frontend/${HOSTNAME}/nodejs
        target: /app
        read_only: true
    command: ["node", "--require", "./patch-https.js" , "server.js"]
    environment:
      - NODE_EXTRA_CA_CERTS=/app/certs/lbtw.ca.starlbtwsys.20230719.20321231.crt
      - HOSTNAME=0.0.0.0   # 讓 server.js 監聽 0.0.0.0 而非容器 ID
    ports:
      - "18843:3000"
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s  # 等待 10 秒後再重啟
        max_attempts: 5  # 最多重啟 5 次
        window: 60s  # 60 秒內最多嘗試 max_attempts 次
      update_config:
        parallelism: 1 # 每次更新 1 個容器
        delay: 5s
        order: start-first
      resources:
        limits: # 個別容器
          cpus: "1"
          memory: "512M"
#networks:
#  webnet:
#    external: true