- tags:
  - rollback
  block:
    - name: Rollback engine 
      include_role:
        name: common
        tasks_from: "base/rollback.yml"
      vars:
        rollback_src: "{{ mca_ap_dir }}/engine/hazelcast"
        rollback_dst: "{{ mca_rollback_dir }}/hazelcast/mca_hazelcast_rollback_{{ timestamp }}"
        rollback_user: "{{ mcaadmin }}"
        rollback_exclude_folders: 
        - "{{ mca_ap_dir }}/engine/hazelcast/code-samples"
        - "{{ mca_ap_dir }}/engine/hazelcast/docs"
        backup_path: "{{ mca_backup_dir }}/hazelcast"
        version_dir: "{{ mca_ap_dir }}"
        
  become: yes
  become_user: mcaadmin  