spring:
  application:
    name:com.line.bank.bxi.bpm.elf.backend
  #  devtools:
  #    restart:
  #      enabled: true
  #      additional-paths: src/main/java
  #    livereload:
  #      enabled: true

server:
  port: 8080
  netty:
    connection-timeout: 30s
    max-http-header-size: 16KB
  error:
    whitelabel.enabled: false

file:
  base:
    directory: /data/bpm-elf-backend/templates

# Actuator
management:
  info:
    java.enabled: true
    os.enabled: true
#    git.enabled: true
#    env.enabled: true
#    ssl.enabled: true
    process.enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  security.enabled: true