spring:
  config:
    import: optional:file:./version.txt
  application:
    name:com.line.bank.bxi.bpm.elf.backend
  #  devtools:
  #    restart:
  #      enabled: true
  #      additional-paths: src/main/java
  #    livereload:
  #      enabled: true

info:
  app:
    name: bpm-elf-backend
    version: ${spring.config.import}
    description: "Spring Boot Actuator Example"

server:
  port: 8080
  netty:
    connection-timeout: 30s
    max-http-header-size: 16KB

file:
  base:
    directory: /data/bpm-elf-backend/templates

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always