
gv_env_name: "dev"

host_name: "{{ host_name }}"
system_code: "bpm-elf"

bpm-elf_ap_version: "0.0.2"

jboss_dir: "{{ gv_sw_dir }}/jboss"
jboss_logs_dir: "{{ gv_logs_dir }}/jboss"

################################################################################
#  Installation flag                                                           #
################################################################################
stack_installation:
  tvdev-ans-lab01: false
  
################################################################################
#  bpm-elf                                                                         #
################################################################################

