---

- hosts: "{{ host_name }}"
  become: yes
  vars_files:
    - "vars/global/all.yml"
    - "vars/sys_common/bpm-elf.yml"
    - "vars/env/{{ site }}{{ env }}/{{ site }}{{ env }}-bpm-elf-stack.yml"
  roles:
    - name: Rollback 
      role: "rollback"
      when:
        - restart_only|default(false)|bool == false